[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18"  # Specify Node.js version
NEXT_TELEMETRY_DISABLED = "1"

# Required for Next.js client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Cache static assets forever (they have hashes)
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML pages - users get fresh content
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

# Cache other assets for a short time
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=3600"

# API routes - no cache
[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"